const STORAGE_KEY = 'daymark-state-v2';
const Core = window.DaymarkCore;
let state = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null') || Core.createEmptyState();
let currentView = 'dashboard';

const $ = selector => document.querySelector(selector);
const profile = () => state.activeProfile ? state.profiles.find(item => item.id === state.activeProfile) : null;
const save = () => localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
const icon = name => ({ sun:'☼', smile:'◌', home:'⌂', paw:'♧', bag:'□', clock:'◷', spark:'✦', money:'$', check:'✓' }[name] || '•');
const formatMinutes = started => { const seconds = Math.max(0, Math.floor((Date.now() - started) / 1000)); return `${String(Math.floor(seconds / 60)).padStart(2,'0')}:${String(seconds % 60).padStart(2,'0')}`; };

function render() {
  if (!state.setupComplete) {
    $('#welcomeRow').classList.add('hidden');
    $('#mainNav').classList.add('hidden');
    $('#appView').innerHTML = setupView();
    bindSetupEvents();
    return;
  }
  $('#welcomeRow').classList.remove('hidden');
  $('#mainNav').classList.remove('hidden');
  const active = profile();
  $('#activeProfileLabel').textContent = active ? active.name : 'Family board';
  $('#profileButton .avatar').className = `avatar avatar-small ${active ? `avatar-${active.color}` : 'avatar-sun'}`;
  $('#profileButton .avatar').textContent = active ? active.initials : 'FB';
  $('#greeting').textContent = active ? `Good morning, ${active.name}.` : 'Family board overview.';
  $('#addTaskButton').classList.toggle('hidden', !active || active.role !== 'Parent profile');
  $('#dateLabel').textContent = new Intl.DateTimeFormat('en-GB',{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase();
  $('#appView').innerHTML = currentView === 'dashboard' ? dashboardView() : currentView === 'tasks' ? tasksView() : currentView === 'rewards' ? rewardsView() : peopleView();
  document.querySelectorAll('.tab').forEach(tab => tab.classList.toggle('active', tab.dataset.view === currentView));
  bindDynamicEvents();
}

function setupView() { return `<section class="setup-screen"><div class="setup-ornament">D</div><p class="eyebrow">WELCOME TO DAYMARK</p><h1>Start with the family anchor.</h1><p class="lede">Create the parent profile first. It keeps the family board private and gives you the keys to add children, tasks and rewards.</p><form id="setupForm" class="form-grid setup-form"><div class="form-row"><label for="parentName">Parent name</label><input id="parentName" required placeholder="e.g. Sam"></div><div class="form-row two"><div class="form-row"><label for="parentInitials">Avatar initials</label><input id="parentInitials" maxlength="2" placeholder="SA"></div><div class="form-row"><label for="parentColor">Avatar colour</label><select id="parentColor"><option value="lavender">Lavender</option><option value="sage">Sage</option><option value="coral">Coral</option><option value="sun">Sun</option></select></div></div><div class="form-row"><label for="parentPassword">Parent password</label><input id="parentPassword" type="password" minlength="4" required placeholder="At least 4 characters"></div><div class="form-row"><label for="parentPasswordAgain">Confirm password</label><input id="parentPasswordAgain" type="password" minlength="4" required placeholder="Type it again"></div><button class="primary-button" type="submit">Create parent profile</button></form></section>`; }
function bindSetupEvents() { $('#setupForm')?.addEventListener('submit', event => { event.preventDefault(); if ($('#parentPassword').value !== $('#parentPasswordAgain').value) return toast('Passwords do not match.'); const created = Core.setupParent(state, { name:$('#parentName').value, password:$('#parentPassword').value, initials:$('#parentInitials').value, color:$('#parentColor').value }); if (!created) return toast('Use a name and a password of at least 4 characters.'); save(); render(); toast('Parent profile created.'); }); }

function dashboardView() {
  const active = profile();
  const mine = state.tasks.filter(task => (!state.activeProfile || task.profile === state.activeProfile) && !task.completed);
  const done = state.tasks.filter(task => (!state.activeProfile || task.profile === state.activeProfile) && task.completed).length;
  const points = active ? active.points : '—';
  const coins = active ? active.coins : '—';
  const streak = active ? `${active.streak} days` : '—';
  return `<div class="stats-grid"><div class="stat-card featured"><span class="stat-label">Today’s progress</span><div class="stat-value">${done} / ${done + mine.length}</div><span class="stat-note">${done ? 'Nice work, keep it moving' : 'Your first win is waiting'}</span></div><div class="stat-card"><span class="stat-label">Points</span><div class="stat-value">${points}</div><span class="stat-note">Check in to view yours</span></div><div class="stat-card"><span class="stat-label">Coins</span><div class="stat-value coin">${coins}</div><span class="stat-note">Check in to view yours</span></div><div class="stat-card"><span class="stat-label">Best streak</span><div class="stat-value">${streak}</div><span class="stat-note">Personal progress</span></div></div>
  <div class="content-grid"><section><div class="section-heading"><h2>Waiting for you</h2><button class="section-action" data-view-target="tasks">See all tasks →</button></div><div class="task-list">${mine.length ? mine.slice(0,4).map(taskTemplate).join('') : '<div class="empty-state">No tasks have been created yet. The parent can add the family\'s first task.</div>'}</div></section><aside class="side-panel"><div class="section-heading"><h2>Family progress</h2></div><div class="quest-card"><div class="quest-top"><span class="quest-kicker">Ready when you are</span><span class="quest-reward">No rewards yet</span></div><h3>Build your rhythm</h3><p>Once tasks are added, completed work and personal quests will appear here.</p><div class="progress-track"><div class="progress-fill" style="width:0"></div></div><div class="progress-label"><span>0 tasks completed</span><span>Start by adding one</span></div></div><div class="streak-card"><span class="stat-label">Profile check-in</span><div class="streak-row"><strong>${active ? `Signed in as ${active.name}` : 'No profile selected'}</strong><button class="section-action" id="checkInButton">Check in →</button></div></div></aside></div>`;
}

function taskTemplate(task) {
  const running = Boolean(task.startedAt);
  const locked = task.min && running && Date.now() - task.startedAt < task.min * 60000;
  const owner = state.profiles.find(item => item.id === task.profile);
  return `<article class="task-row ${running ? 'running' : ''}" data-task-id="${task.id}"><div class="task-icon ${task.icon === 'home' ? 'coral' : task.icon === 'sun' ? 'yellow' : task.icon === 'smile' ? 'purple' : ''}">${icon(task.icon)}</div><div><div class="task-meta"><p class="task-title">${task.title}</p><span class="task-tag">${task.tag}</span></div><p class="task-subtitle">${task.subtitle}${owner && state.activeProfile === 'parent' ? ` · ${owner.name}` : ''}${running ? ` · <span class="timer">${formatMinutes(task.startedAt)} elapsed</span>` : ''}</p></div><div class="task-actions"><span class="task-time">${task.due}</span>${running ? `<button class="start-button complete" data-action="complete" ${locked ? 'disabled title="Minimum time not reached"' : ''}>Complete</button>` : `<button class="start-button" data-action="start">Start</button>`}<button class="menu-button" data-action="menu" aria-label="Task options">···</button></div></article>`;
}

function tasksView() { const active = profile(); const tasks = state.tasks.filter(task => !state.activeProfile || active?.role === 'Parent profile' || task.profile === state.activeProfile); return `<div class="section-heading"><h2>All tasks</h2>${active?.role === 'Parent profile' ? '<button class="primary-button" id="inlineAddTask">+ Add task</button>' : ''}</div><div class="task-list">${tasks.length ? tasks.map(task => task.completed ? `<article class="task-row"><div class="task-icon">✓</div><div><p class="task-title">${task.title}</p><p class="task-subtitle">Completed today</p></div><div class="task-actions"><span class="task-tag">Done</span></div></article>` : taskTemplate(task)).join('') : '<div class="empty-state">No tasks have been created yet. The parent can add the family\'s first task.</div>'}</div>`; }
function rewardsView() { return `<div class="section-heading"><div><h2>Rewards shop</h2><p class="lede">Trade your progress for things that feel good.</p></div>${profile()?.role === 'Parent profile' ? '<button class="primary-button" id="editRewards">Manage rewards</button>' : ''}</div>${state.rewards.length ? `<div class="reward-grid">${state.rewards.map(reward => `<article class="reward-card"><div class="task-icon">${icon(reward.icon)}</div><h3>${reward.name}</h3><p>${reward.description}</p><span class="reward-cost">${reward.cost} ${reward.kind}</span><button class="section-action" data-redeem="${reward.name}">Redeem →</button></article>`).join('')}</div>` : '<div class="empty-state">No rewards have been created yet. The parent can add rewards when the family is ready.</div>'}`; }
function peopleView() { const active = profile(); return `<div class="section-heading"><div><h2>People</h2><p class="lede">Manage who is part of your family board.</p></div>${active?.role === 'Parent profile' ? '<button class="primary-button" id="addProfile">+ Add child</button>' : ''}</div><div class="people-grid">${state.profiles.map(person => `<article class="person-card"><span class="avatar avatar-medium avatar-${person.color}">${person.initials}</span><div class="person-info"><div class="person-name">${person.name}</div><div class="person-role">${person.role}</div></div><span class="person-points">${person.points} pts</span></article>`).join('')}</div>`; }

function showModal(content) { $('#modalContent').innerHTML = content; $('#modalBackdrop').classList.remove('hidden'); }
function closeModal() { $('#modalBackdrop').classList.add('hidden'); }
function taskForm() { return `<h2 id="modalTitle">Add a task</h2><p class="modal-intro">Make the next step clear and achievable.</p><form id="taskForm" class="form-grid"><div class="form-row"><label for="taskName">Task name</label><input id="taskName" required placeholder="e.g. Put away washing"></div><div class="form-row two"><div class="form-row"><label for="taskType">Type</label><select id="taskType"><option value="adhoc">Ad hoc</option><option value="recurring">Recurring</option><option value="group">Task group</option></select></div><div class="form-row"><label for="taskProfile">For</label><select id="taskProfile">${state.profiles.filter(p => p.role !== 'Parent profile').map(p => `<option value="${p.id}">${p.name}</option>`).join('')}</select></div></div><div class="form-row two"><div class="form-row"><label for="taskDue">Due</label><input id="taskDue" placeholder="Today or 8:30 AM"></div><div class="form-row"><label for="taskMin">Minimum minutes</label><input id="taskMin" type="number" min="0" value="0"></div></div><div class="form-footer"><button type="button" class="secondary-button" id="cancelModal">Cancel</button><button class="primary-button">Create task</button></div></form>`; }
function profileForm() { return `<h2 id="modalTitle">Create a child account</h2><p class="modal-intro">Give them a short PIN they can use to check in quickly.</p><form id="profileForm" class="form-grid"><div class="form-row"><label for="profileName">Name</label><input id="profileName" required placeholder="e.g. Jamie"></div><div class="form-row two"><div class="form-row"><label for="profileInitials">Avatar initials</label><input id="profileInitials" maxlength="2" placeholder="JA"></div><div class="form-row"><label for="profileColor">Avatar colour</label><select id="profileColor"><option value="sage">Sage</option><option value="coral">Coral</option><option value="lavender">Lavender</option><option value="sun">Sun</option></select></div></div><div class="form-row"><label for="profilePin">Child PIN</label><input id="profilePin" type="password" minlength="4" inputmode="numeric" required placeholder="At least 4 digits"></div><div class="form-footer"><button type="button" class="secondary-button" id="cancelModal">Cancel</button><button class="primary-button">Create child account</button></div></form>`; }
function authenticateView(profileId) { const selected = state.profiles.find(item => item.id === profileId); return `<h2 id="modalTitle">${selected.name} is checking in</h2><p class="modal-intro">Enter the ${selected.role === 'Parent profile' ? 'parent password' : 'child PIN'} to open this profile.</p><form id="authForm" class="form-grid"><input type="hidden" id="authProfile" value="${profileId}"><div class="form-row"><label for="credential">${selected.role === 'Parent profile' ? 'Password' : 'PIN'}</label><input id="credential" type="password" required autofocus></div><div class="form-footer"><button type="button" class="secondary-button" id="cancelModal">Cancel</button><button class="primary-button">Check in</button></div></form>`; }

function bindDynamicEvents() { document.querySelectorAll('[data-action]').forEach(button => button.addEventListener('click', () => taskAction(button))); document.querySelectorAll('[data-view-target]').forEach(button => button.addEventListener('click', () => { currentView='tasks'; render(); })); document.querySelectorAll('[data-redeem]').forEach(button => button.addEventListener('click', () => toast(`${button.dataset.redeem} saved to your wishlist.`))); $('#inlineAddTask')?.addEventListener('click', () => showModal(taskForm())); $('#addProfile')?.addEventListener('click', () => showModal(profileForm())); $('#editRewards')?.addEventListener('click', () => toast('Reward editing is ready for your parent profile.')); }
function taskAction(button) { const taskId = Number(button.closest('[data-task-id]').dataset.taskId); const task = state.tasks.find(item => item.id === taskId); if (button.dataset.action === 'start') { if (!Core.startTask(state, taskId)) return toast('Only the assigned profile can start this task.'); toast(`${task.title} started.`); } else if (button.dataset.action === 'complete') { if (!Core.completeTask(state, taskId)) return toast('The minimum time has not been reached yet.'); toast('Great work. +20 points and +2 coins.'); } else { toast('Task options will be available in the next update.'); } save(); render(); }
function toast(message) { const element = $('#toast'); element.textContent = message; element.classList.remove('hidden'); setTimeout(() => element.classList.add('hidden'), 2600); }

document.querySelectorAll('.tab').forEach(tab => tab.addEventListener('click', () => { currentView = tab.dataset.view; render(); }));
$('#addTaskButton').addEventListener('click', () => showModal(taskForm()));
$('#profileButton').addEventListener('click', () => showModal(`<h2 id="modalTitle">Who is checking in?</h2><p class="modal-intro">Choose a profile to see personal tasks, or stay on the family board.</p><div class="profile-options"><button class="profile-option" data-profile="overview"><span class="avatar avatar-medium avatar-sun">FB</span><span><strong>Family board</strong><small>Overview, no profile selected</small></span></button>${state.profiles.map(p => `<button class="profile-option" data-auth-profile="${p.id}"><span class="avatar avatar-medium avatar-${p.color}">${p.initials}</span><span><strong>${p.name}</strong><small>${p.role}</small></span></button>`).join('')}</div>`));
$('#settingsButton').addEventListener('click', () => toast('Your data stays on this device.')); $('#modalClose').addEventListener('click', closeModal); $('#modalBackdrop').addEventListener('click', event => { if (event.target.id === 'modalBackdrop') closeModal(); });
document.addEventListener('click', event => { if (event.target.id === 'cancelModal') closeModal(); });
document.addEventListener('click', event => { const profileButton = event.target.closest('[data-profile]'); const authButton = event.target.closest('[data-auth-profile]'); if (profileButton) { Core.logout(state); save(); closeModal(); render(); } if (authButton) showModal(authenticateView(authButton.dataset.authProfile)); });
document.addEventListener('submit', event => { if (event.target.id === 'authForm') { event.preventDefault(); if (!Core.authenticate(state, $('#authProfile').value, $('#credential').value)) return toast('That credential did not match.'); save(); closeModal(); render(); toast(`Checked in as ${profile().name}.`); } if (event.target.id === 'taskForm') { event.preventDefault(); const task = Core.addTask(state, { id:Date.now(), title:$('#taskName').value, subtitle:$('#taskType').value === 'recurring' ? 'Repeats on your schedule' : 'Added today', type:$('#taskType').value, icon:'home', tag:$('#taskType').value === 'adhoc' ? 'Ad hoc' : $('#taskType').value === 'group' ? 'Routine' : 'Recurring', profile:$('#taskProfile').value, due:$('#taskDue').value || 'Today', min:Number($('#taskMin').value) || 0 }); if (!task) return toast('Only the parent can add tasks.'); save(); closeModal(); render(); toast('Task added to the board.'); } if (event.target.id === 'profileForm') { event.preventDefault(); const child = Core.addChild(state, { name:$('#profileName').value, pin:$('#profilePin').value, initials:$('#profileInitials').value, color:$('#profileColor').value }); if (!child) return toast('Use a name and a PIN of at least 4 characters.'); save(); closeModal(); render(); toast(`${child.name} now has a profile.`); } });
setInterval(() => { document.querySelectorAll('.running').forEach(row => { const task = state.tasks.find(item => item.id === Number(row.dataset.taskId)); const timer = row.querySelector('.timer'); if (task?.startedAt && timer) timer.textContent = `${formatMinutes(task.startedAt)} elapsed`; }); }, 1000);
render();